### ISSUE TITLE
[Sprint 2, 3] 동기화 문제로 인한 차후 BubbleService 재작성의 필요성

### ISSUE THREAD

**Issue by lsw8075** [swsnu/swpp17-team1#1]
쓰다 보니 알았는데, 이번 sprint 2에서 in-memory data service를 쓸 필요가 없다고 생각합니다.
우리가 이것을 쓰기로 한 이유는, bubble.service를 재작성하는 수고를 덜기 위해서인데, 다시 검토해 보니 우리가 in-memory data service(줄여서 mock backend라 언급)를 쓰더라도 sprint 3에서는 다시 작성해야 한다는 문제가 있습니다. 

위키의 현재 버전을 기준으로, 먼저 mock backend를 사용한 우리의 처음 구현 구상은 다음과 같습니다.
현재 구현은, 처음에 constructor에서 bubbleList를 쫙 받아 놓고 bubble에 대한 operation이 들어오면
i) frontend가 들고 있는 정보를 업데이트 ii) http request로 mock backend가 들고 있는 정보를 업데이트
두 가지 정보를 동시에 업데이트합니다.

sprint 3에서 실제 backend가 작동할 때를 생각해 봅니다.

다음과 같은 상황을 가정해 봅니다: User는 A, B, C가 있습니다. 각각 popBubble과 createBubble, getBubbleList함수를 호출합니다. 버블 구조는 다음과 같습니다: 1( 2, 3( 4, 5, 6 ) ,7 )
1. user A가 popBubble(3) 함수를 호출합니다. 프런트의 데이터를 알맞게 업데이트하며, 요청은 여러 개의 PUT 요청(3번 버블들의 자식 버블들 각각의 parent를 1번 버블로 바꾸는 작업, 1번 bubble의 children list를 업데이트하는 작업) 과 하나의 DELETE 요청(3번 버블을 삭제하는 작업)으로 구성됩니다. 각각의 요청 사이에 다른 User의 요청이 끼어들 수 있습니다.

2. 1번 작업이 완료되기 전까지 (더하여, 다시 정보를 받아오기 전까지) B는 이 버블이 pop되고 있다는 것을 모릅니다. 8번 버블을 3번 버블  밑에 만들기 ( 1( 2, 3( 4, 8, 5, 6 ) ,7 )을 원할 때 )에 만들기 위해 createBubble(3, 1, 'Bubble no.8')이렇게 호출한다고 해 봅시다. 하지만 1번 작업은 이제 막 5번 버블의 PUT 작업을 처리했습니다. 1번의 children list에는 4, 5번 버블이 추가되지 않았는데 4, 5번 버블은 벌써 1번 버블을 부모로 가지고, 3번 버블은 6번 버블을 자식으로 가진 채로 8번 버블을 자식으로 가지게 되었습니다. 이 상태에서 C가 접속해getBubbleList를 호출하고 잘못된 정보를 가져갑니다.. 꼬이는군요. 
이런 문제를 줄이기 위해서는 한 operation이 백엔드 측에서 한 번의 요청으로 atomic하게 처리되어야 합니다. 이렇게 되면  현재의 여러 자료를 한 번의 요청으로 동시에 처리할 수 없는 mock backend를 위해 만들어진 현재의 API 스펙이, 한 번의 요청에 하나의 operation을 처리하도록 바뀌어야 합니다. 자연히 그 API를 기반으로 하는 현재의 bubble.service 스펙은 재작성될 수밖에 없습니다.

그러므로 결론은, 어차피 싹 다시 작성해야 하는 서비스인데, 테스트를 작성하는 수고를 조금이라도 덜고자 mock backend 없이 프런트의 bubble.service만 정보를 들고 있게 해도 될 것 같습니다.

**Comment by yuyupopo** [comment]
우리 bubbleAPI가 손 봐야 하는 점이 많네. sprint3에는 이걸 최우선으로 하자.
각 request당 어떤 정보가 가고 오는지 적어야함
확실히 mockdb로 모든걸 하긴 어렵겠네. 이제 이해했다. 고마워 수고했어

**Comment by lsw8075** [comment]
The design considerations for bubble model and API

To minimize situation that request fails, the bubble model at backend be designed to minimize the number of bubbles that the operation involves
(ex) By storing childBubbleList instead of location and parentID, user need not be updating location information of all the uncle bubbles when creating or deleting bubble.

maybe we can use Model inheritance of Abstract base classes..

bubble model at backend should contain:

id : auto
latestUpdate : long (timestamp of microsecond)
getTime : Array??? of int, for each user...
editlock : boolean
owner : foreignkey to User, can be null
content : text, can be null
childBubbleList : one-to-many????


hmm.. one-to-many is unavailable in django.

instead we can use CommaSeparatedIntegerField but it is not fine..



foreignKey to BubbleLocationInfo
other model should contain foreign keys:

Comment.article


the information get through bubbleAPI:

childID

the information frontend can generate about bubbles.:

parentID
parentBubbleList
childBubbleList
location

the information frontend can get through other apis:

comments

how to???
suggestBbble

**Comment by lsw8075** [comment]
getTime 에 ManyToManyField through try 해보기

**Comment by lsw8075** [comment]
옛날 이슈. 지금은 완전히 웹소켓으로 바뀌었으니 닫음.
