### ISSUE TITLE
createBubble시에 isOwned 정보가 필요합니다

### ISSUE THREAD

**Issue by ss01363** [swsnu/swpp17-team1#48]
backend에서는 do_create_bubble 할때 is_owned정보를 필요로하는데
프런트에서 생각해보면 또 에딧 끝날때 isOwned를 지정하는것이 자연스러운 느낌?
그럼 이 두가지 중 하난데

1) front에서 유저가 create할때 isOwned를 물어보기
2) do_create_bubble시에 일단 is_owned를 true로 넣어놓고 에딧 끝날때 유저한테 물어보고 해당 내용을 업데이트

어느쪽으로 갈것입니까?

https://github.com/swsnu/swpp17-team1/blob/0e6b082b4dc745cde79dac8b7f6c16f140d3246c/frontend/src/app/service/bubble.service.ts#L36

**Comment by lucetre** [comment]
사용자가 자신이 곧 쓸 내용을 미리 알아서 edit lock을 걸어 놓는다고 생각되진 않아.
2번째 구현이 맞는 것 같아.

**Comment by yuyupopo** [comment]
나도 2번.

**Comment by ss01363** [comment]
굿굿 그렇게 가겠슴당
