### ISSUE TITLE
[SPRINT4] front end AGENDA

### ISSUE THREAD

**Issue by yuyupopo** [swsnu/swpp17-team1#54]
# 1st week : refactoring / arrange feature list / test  / finish sangjun board
make branch (from master) `sprint4-front` => do refactor
write tests, its okay to be blank

# 2st week : implement all features listed in 1st week  

## frontend must be almost complete by this sprint

**Comment by yuyupopo** [comment]
@lucetre 오늘 밤에 hangout으로 회의 희망 (10분)  
sprint4-front에서 새 브랜치 파서 sangjun board 작업 바람

**Comment by yuyupopo** [comment]
bubble list view의 'style'부분은 대부분 bubble model 쪽에 넣는게 가능할 듯

**Comment by yuyupopo** [comment]
목요일까지 refactoring & sangjunboard, & 리스트 정리 & 기타 (안쓰는 브랜치 정리 등) 끝냈으면 함

**Comment by lucetre** [comment]
이따 11시쯤에 회의하자
