### ISSUE TITLE
Update preview after user delete bubbles

### ISSUE THREAD

**Issue by yuyupopo** [swsnu/swpp17-team1#8]
bubble delete => update preview not working

**Comment by yuyupopo** [comment]
make FAQ in wiki and in landing page

**Comment by yuyupopo** [comment]
https://stackoverflow.com/questions/34714462/updating-variable-changes-in-components-from-a-service-with-angular2
https://angular.io/guide/component-interaction#parent-and-children-communicate-via-a-service

**Comment by yuyupopo** [comment]
@lucetre board service에 적절한 이벤트 넣어서 bubble list에서 preview로 넘기는게 어떨까 싶음

**Comment by lucetre** [comment]
preview tab 클릭시 발생되는 이벤트를 가지고 update하려 하는데 view board compoenent ts에서 preview component를 view child로 가져오는게 안됨됨

**Comment by lucetre** [comment]
compiler.es5.js:1694 Uncaught Error: Can't resolve all parameters for PreviewComponent: (?).
    at syntaxError (compiler.es5.js:1694)
    at CompileMetadataResolver.webpackJsonp.../../../compiler/@angular/compiler.es5.js.CompileMetadataResolver._getDependenciesMetadata (compiler.es5.js:15781)

**Comment by yuyupopo** [comment]
지금 현재 문제 되는 코드 푸쉬 되어 있음?

**Comment by lucetre** [comment]
모르고 브랜치 sprint3-editboard에 주석처리하고 올려놨어 viewboard

**Comment by yuyupopo** [comment]
circular dependency 문제인듯 해결해서 푸쉬함

**Comment by yuyupopo** [comment]
우리가 보면 preview가 view board에서 export된 모델, 함수를 가져다 쓰는데, viewboard가 preview를 import하면 circular dependency 문제 발생 그래서 preview가 viewboard가 아닌 상위 parent에서 가져옴
이러한 circular dependenc가 저번부터 문제 되니까 금요일 회의때 이야기 해서 구조를 다시 잡아야 할 듯 (누가 무엇을 상속)

**Comment by yuyupopo** [comment]
issue closed delete bug created by service logic not preview component
